// Embed the stylesheet as JS strings so the renderer has no filesystem
// dependency (works in the browser as well as Node). Reads styles/*.css and
// emits src/styles.js. Run via `npm run generate`; the committed output is
// checked against a fresh build by test/styles.test.js.

import { readFileSync, writeFileSync, realpathSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { argv } from "node:process";
import { fileURLToPath } from "node:url";

const PKG = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const STYLES_DIR = join(PKG, "styles");
export const OUT = join(PKG, "src", "styles.js");

const BANNER =
  "// Generated by scripts/generate-styles.mjs from styles/*.css.\n" +
  "// Do not edit by hand.\n";

/** The `src/styles.js` source — the stylesheet as escaped JS string constants. */
export function buildStylesModule() {
  const read = (f) => readFileSync(join(STYLES_DIR, f), "utf8");
  return (
    BANNER +
    `\nexport const variablesCss = ${JSON.stringify(read("variables.css"))};\n` +
    `export const utilitiesCss = ${JSON.stringify(read("utilities.css"))};\n` +
    `export const viewCss = ${JSON.stringify(read("view.css"))};\n`
  );
}

const invokedDirectly =
  argv[1] !== undefined && realpathSync(argv[1]) === fileURLToPath(import.meta.url);
if (invokedDirectly) {
  writeFileSync(OUT, buildStylesModule());
  process.stdout.write("Generated src/styles.js\n");
}
