// Embed the stylesheet as a JS string so the renderer has no filesystem
// dependency (works in the browser as well as Node). Reads styles/invoice.css
// and emits src/styles.js. Run via `npm run generate`.

import { readFileSync, writeFileSync, realpathSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { argv } from "node:process";
import { fileURLToPath } from "node:url";

const PKG = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const STYLES_DIR = join(PKG, "styles");
export const OUT = join(PKG, "src", "styles.js");

const BANNER =
  "// Generated by scripts/generate-styles.mjs from styles/invoice.css.\n" +
  "// Do not edit by hand.\n";

/** The `src/styles.js` source — the invoice stylesheet as an escaped JS string. */
export function buildStylesModule() {
  const css = readFileSync(join(STYLES_DIR, "invoice.css"), "utf8");
  return `${BANNER}\nexport const invoiceCss = ${JSON.stringify(css)};\n`;
}

const invokedDirectly =
  argv[1] !== undefined && realpathSync(argv[1]) === fileURLToPath(import.meta.url);
if (invokedDirectly) {
  writeFileSync(OUT, buildStylesModule());
  process.stdout.write("Generated src/styles.js\n");
}
