/** Generate the committed artifacts from the canonical schema.
 *
 *  Inputs : data/invoice-schema.json  (the canonical EN 16931 simplified-invoice
 *           contract — the language-neutral source of truth; Python and other
 *           consumers read the same JSON file).
 *  Outputs: generated/schema.ts        — the schema as a runtime object, so the
 *           validators compile it without a filesystem read at import time.
 *           generated/invoice-types.ts — TypeScript types derived from the
 *           schema via json-schema-to-typescript.
 *
 *  Both outputs are committed; test/artifacts.test.ts asserts they match a
 *  fresh regeneration. Run via `npm run generate`. */

import { readFileSync, realpathSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { argv } from "node:process";
import { fileURLToPath } from "node:url";
import { compile } from "json-schema-to-typescript";

const PKG = resolve(dirname(fileURLToPath(import.meta.url)), "..");
export const SCHEMA_PATH = join(PKG, "data", "invoice-schema.json");
export const GEN_DIR = join(PKG, "generated");

const BANNER =
  "// Generated by @facturion/invoice generate.ts from data/invoice-schema.json.\n" +
  "// Do not edit by hand.\n";

export function readSchema(): Record<string, unknown> {
  return JSON.parse(readFileSync(SCHEMA_PATH, "utf8")) as Record<string, unknown>;
}

/** The `generated/schema.ts` source — the schema as a runtime object. */
export function schemaModule(schema: Record<string, unknown>): string {
  return `${BANNER}\nexport const invoiceSchema: Record<string, unknown> = ${JSON.stringify(schema, null, 2)};\n`;
}

/** The `generated/invoice-types.ts` source — types derived from the schema. */
export async function typesModule(schema: Record<string, unknown>): Promise<string> {
  const ts = await compile(schema as Parameters<typeof compile>[0], "Invoice", {
    bannerComment: BANNER.trimEnd(),
    additionalProperties: false,
    declareExternallyReferenced: true,
  });
  return ts.endsWith("\n") ? ts : `${ts}\n`;
}

export async function buildArtifacts(): Promise<{ schemaTs: string; typesTs: string }> {
  const schema = readSchema();
  return { schemaTs: schemaModule(schema), typesTs: await typesModule(schema) };
}

async function main(): Promise<void> {
  const { schemaTs, typesTs } = await buildArtifacts();
  writeFileSync(join(GEN_DIR, "schema.ts"), schemaTs);
  writeFileSync(join(GEN_DIR, "invoice-types.ts"), typesTs);
  process.stdout.write("Generated generated/schema.ts + generated/invoice-types.ts\n");
}

// Run only when invoked directly (so importing this module from the artifacts
// test does not rewrite the committed files).
const invokedDirectly =
  argv[1] !== undefined && realpathSync(argv[1]) === fileURLToPath(import.meta.url);
if (invokedDirectly) await main();
